// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairExpensesAPI.Data;

#nullable disable

namespace PairExpensesAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240307142846_ChangesToUsers")]
    partial class ChangesToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PairXpensesAPI.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PairXpensesAPI.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PairXpensesAPI.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PairRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cody1",
                            PairRole = "pair1",
                            Password = "default_diffindb",
                            Username = "codyone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cody2",
                            PairRole = "pair1",
                            Password = "default_diffindb",
                            Username = "codytwo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Daniel",
                            PairRole = "pair2",
                            Password = "default_diffindb",
                            Username = "lightroast"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mari",
                            PairRole = "pair2",
                            Password = "default_diffindb",
                            Username = "maritza.30.r"
                        });
                });

            modelBuilder.Entity("PairXpensesAPI.Debt", b =>
                {
                    b.HasOne("PairXpensesAPI.User", null)
                        .WithMany("Debts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairXpensesAPI.Payment", b =>
                {
                    b.HasOne("PairXpensesAPI.User", null)
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairXpensesAPI.User", b =>
                {
                    b.Navigation("Debts");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
